apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: edit
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: mongo-sa
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-27T00:28:17Z"
  name: mongo-sa
  namespace: rocket-chat-dev